name: platform_font_plugin
description: "A new Flutter plugin (Android only) used to get the device current font type"
version: 1.0.1
homepage: 
repository: https://github.com/Raks-Javac/platform_font_plugin.git

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.example.platform_font_plugin
        pluginClass: MyFontPlugin

